export const options = {
  dinner: [
    "Nermin's Delicious Home Cooked Steak",
    "Kinns",
    "Nandos",
    "Pizza",
    "Mexican",
    "* Insert Some Fancy Restaurant *",
    "Wing It",
  ] as const,
  drinks: [
    "Canadian Club & Dry",
    "Beer",
    "Wine",
    "Cocktails 👀",
    "Wild Boar Bourbon & Cola",
    "Cruisers",
    "Pink Gin",
    "Hard Rated",
    "Billson's",
    "Howler Head & Cola",
    "Water (really?)",
  ] as const,
  snacks: [
    "Froyo",
    "Chocolate",
    "Popcorn",
    "Chips",
    "Nermin",
    "San Churros",
    "Ice Cream",
    "Strawberries",
    "Strawberries + Chocolate",
    "Grapes (extra)",
    "Cake",
  ] as const,
  activity: [
    "Anaconda",
    "Netflix (and chill)",
    "Bars / Clubs",
    "Shopping",
    "Walk",
    "Late Night Bike Ride",
    "Face Masks / Spa Day",
    "Paint and sip",
    "Karaoke",
    "Trip planning",
    "Weekend stay",
    "Games Night",
    "Pool",
    "Scrapbooking",
    "Baking",
  ] as const,
};
